### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by moonylead1** [moonylead1/uni2024oop#1]
Lab2
- [x] team management plus delete teams on players 
- [x] team show with members
- [x] create new teams inside app
- [x] Assign/deassign trainers
- [x] create cool_out() all in one drop info
- [x] Handle the errors while loading "bad templated txt"
- [x] Send user a message if error load happened
