### ISSUE TITLE
lab4 to-do List

### ISSUE THREAD

**Issue by moonylead1** [moonylead1/uni2024oop#2]
- [x] Add Team or mark for ingame players
- [x] Change or add changes for Design Model 
- [x] Add an exception class and manage it

**Comment by moonylead1** [comment]
- [x] add python realization
